// Offline fallback. Reddit rate limits by IP and college wifi tends to sit
// behind a shared one, so this keeps the dashboard demoable when the fetch
// fails. The banner in the UI makes it obvious this isn't live data.
const TITLES = [
  ['My grandmother finally finished her first marathon at 71 and we are so proud', 48200, 1840],
  ['This wholesome exchange between a barista and a regular made my whole week', 31500, 620],
  ['Absolutely gorgeous sunrise over the harbour this morning', 27800, 410],
  ['After three years of rejections I finally got the job offer', 26100, 1520],
  ['My rescue dog smiled for the first time today and I am not okay', 24700, 980],
  ['Terrible news about the layoffs, half the team is gone', 21400, 3100],
  ['This scam has been going around and it cost my dad his savings', 19800, 2450],
  ['Why is the new update so broken? Nothing works properly anymore', 18900, 4200],
  ['Beautiful little bookshop that survived the recession, please support them', 17600, 340],
  ['The customer service here is absolutely awful and nobody cares', 16400, 890],
  ['TIL that honey found in ancient tombs was still edible', 15900, 720],
  ['What is a small thing that instantly ruins your day?', 15100, 8600],
  ['Amazing performance last night, easily the best show I have seen', 14800, 430],
  ['Cringe marketing email from a company that should know better', 14200, 1100],
  ['My homemade sourdough finally turned out perfect after 20 tries', 13700, 560],
  ['This lawsuit is going to drag on for years and nobody wins', 13100, 1980],
  ['Congrats to everyone who graduated this weekend', 12800, 390],
  ['The outage lasted nine hours and support never replied', 12300, 1670],
  ['Underrated album that deserves so much more attention', 11900, 880],
  ['Genuinely hilarious response from the support team', 11400, 250],
  ['What is the most useless fact you know?', 11000, 5400],
  ['Sketchy landlord is refusing to return the deposit, what do I do', 10700, 1420],
  ['Adorable kitten adopted us in the parking lot last night', 10300, 470],
  ['Toxic work culture is driving everyone out of this industry', 9900, 2300],
  ['Finally paid off my student loans after eight years', 9600, 810],
  ['Weekly discussion thread', 9200, 340],
  ['This masterpiece has been sitting in a garage for 40 years', 8900, 520],
  ['Disappointed with the quality, it broke within a week', 8600, 640],
  ['My neighbour shovelled my driveway without being asked', 8200, 290],
  ['Rant: the parking situation here is a complete disaster', 7900, 1150],
  ['Stunning photo of the eclipse from my back garden', 7600, 210],
  ['Anyone else feel like the prices have gotten ridiculous?', 7300, 2900],
  ['Great little guide for beginners, wish I had this last year', 7000, 330],
  ['The recall notice came two months too late', 6800, 740],
  ['Happy to report the surgery went perfectly', 6500, 480],
  ['Why does every app want a subscription now', 6200, 1830],
  ['Sunday market haul, everything was so fresh', 5900, 160],
  ['Frustrating experience trying to cancel my plan', 5600, 590],
  ['My son drew this for his teacher and she cried', 5300, 220],
  ['Serious question: is the drama in this community getting worse?', 5000, 1240],
  ['Clutch finish in the last 30 seconds, what a game', 4800, 670],
  ['Warning about the fake listings going around', 4500, 380],
  ['Cozy reading nook I built over the weekend', 4200, 190],
  ['Meltdown in the comments over a minor rule change', 3900, 1560],
  ['Small win: I finally organised the garage', 3600, 140],
  ['Monthly questions thread, ask anything here', 3300, 920],
  ['The trailer looks incredible, cannot wait', 3000, 410],
  ['Deeply disappointing end to an otherwise good season', 2700, 830],
  ['Free workshop this Saturday, everyone welcome', 2400, 95],
  ['Update on yesterday: everything worked out fine', 2100, 260],
]

export const SAMPLE_SUB = 'sample'

export const samplePosts = TITLES.map(([title, ups, comments], i) => ({
  id: `sample-${i}`,
  rank: i + 1,
  title,
  author: 'sample_user',
  ups,
  comments,
  created: Date.now() - (i + 1) * 47 * 60 * 1000,
  link: 'https://www.reddit.com/',
  flair: null,
  nsfw: false,
}))
